### ISSUE TITLE
VPN not registering

### ISSUE THREAD

**Issue by Saberawr** [lunyx/CasualMeter#43] opened 2015-12-15 06:56 UTC
I've edited my server-overrides.txt file properly [server-overrides.txt](https://github.com/lunyx/CasualMeter/files/62134/server-overrides.txt) on a clean install of the software and it doesn't detect either of the IPs I have (which I've found properly through my resource monitor)

I've tried attacking moalith birds near old naga-daily to detect something but nothing shows up. The only other thing I've modified is my settings.json file, changing inactivityResetDuration to 300 instead of 30.

I've tried to replicate this problem in other dps meters to no avail (works fine there but not here). CasualMeter also detects me logging in / records my DPS if I do not connect through my VPN

**Comment by lunyx** [comment] 2015-12-16 00:17
The server-overrides.txt is just there for support of detecting packets from a different IP if it happens to follow the same packet structure.  It doesn't guarantee that it'll work on a VPN as often times, many of them have their own layer wrapping around the packets.

**Comment by Saberawr** [comment] 2015-12-16 08:48
I use BattlePing if that helps, willing to help you test if you'd like to resolve the issue if I can be of assistance. It's got a free trial if you prefer to test things yourself which lasts indefinitely.

**Comment by lunyx** [comment] 2015-12-17 16:35
Unfortunately, this isn't something that I'm interested in spending a lot of time on.  I've already spent a good amount of time trying to see what the cause was, but I don't really have any good solution in place.  Perhaps another developer who has issues with BattlePing or WTFast can step in and contribute for this.

**Comment by KaneTW** [comment] 2015-12-27 05:08
Check #47. That fixed this for me.

**Comment by KaneTW** [comment] 2015-12-27 05:09
Long story short the way Battleping works makes WinPcap (which works on layer 2) only see the encrypted packets. In order to see the actual unencrypted data, we need to sniff at layer 3 (raw sockets).

**Comment by lunyx** [comment] 2015-12-27 09:26
Merged in #47. Details on usage here: https://github.com/lunyx/CasualMeter/wiki/Using-VPN's

**Closed by lunyx** 2015-12-27 09:26 UTC
Labels: help wanted
